stages:
  - test
  - deploy

sqlite3_latest:
  stage: test
  image: python:3.12
  script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - $HOME/.local/bin/poetry config virtualenvs.create false
    - rm poetry.lock
    - sed -i 's/^python = ".*$/python = "^3.11"/' pyproject.toml
    - cat pyproject.toml
    - $HOME/.local/bin/poetry install --no-interaction
    - scripts/update_translations.sh
    - python -Wd tests.py -v

sqlite3_latest_pip:
  stage: test
  image: python:3.10
  script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - pip --disable-pip-version-check --no-cache-dir install --upgrade pip
    - pip --disable-pip-version-check --no-cache-dir install "babel<3"
    - scripts/update_translations.sh
    - $HOME/.local/bin/poetry build
    - rm -rf taguette
    - pip --disable-pip-version-check --no-cache-dir install --upgrade dist/taguette-*.whl bcrypt "aiohttp>=3.4,<4"
    - python -Wd tests.py -v
