"""Add parent_id column to tags table

Revision ID: 63d7ca28fc0c
Revises: db5e31a0233d
Create Date: 2024-10-12 15:20:57.692684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d7ca28fc0c'
down_revision = 'db5e31a0233d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tags_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tags_parent_id_tags'), 'tags', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tags_parent_id_tags'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tags_parent_id'))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
